### ISSUE TITLE
swaylock pam module installed to incorrect location

### ISSUE THREAD

**Issue by ghost** [zetok/zetok-overlay#3]
Hi,

When installing the sway package on my system, swaylock has a bug where entering the correct password doesn't unlock the screen.

I ran strace on swaylock and saw that it checks the following locations:
/etc/pam.d/swaylock
/usr/lib/pam.d/swaylock
... and failing that uses /etc/pam.d/other which doesn't work.

Meanwhile, the package installs /usr/etc/pam.d/swaylock , which when copied to /etc/pam.d/swaylock causes swaylock to work fine.

I think this is an issue with the ebuild because I don't think the sway repo specifies the install location of the swaylock pam file anywhere.

**Comment by zetok** [comment]
Thanks, fixed in 70898fa1e9a93611af6b5d2a070899207e8a9280
